# Generated by Django 4.1.1 on 2022-09-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_aboutsiteconfig_seo_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsiteconfig",
            name="markdown_content",
            field=models.TextField(
                blank=True,
                help_text="Main About-Content. Markdown supported",
                max_length=4095,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(help_text="Markdown supported.", max_length=4095),
        ),
    ]
