# Generated by Django 4.1 on 2022-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialaccountsconfig",
            old_name="isntagramm",
            new_name="instagram",
        ),
        migrations.RenameField(
            model_name="socialaccountsconfig",
            old_name="mastadon",
            new_name="mastodon",
        ),
        migrations.AddField(
            model_name="socialaccountsconfig",
            name="rss",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
